export const SHORTEN_URL_REQUEST = 'SHORTEN_URL_REQUEST';
export const SHORTEN_URL_SUCCESS = 'SHORTEN_URL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';
export const CLEAR_URLS = 'CLEAR_URLS';
